<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <ApplicationIcon>Assets\applied-nanotechnology.ico</ApplicationIcon>
        <GenerateDocumentationFile>True</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="Assets\applied-nanotechnology.ico" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.3.13" />
        <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.3.13" />
        <PackageReference Include="Avalonia.Desktop" Version="11.3.13" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.13" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.13" />
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Include="Avalonia.Diagnostics" Version="11.3.13">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.1" />
        <PackageReference Include="Emgu.CV" Version="4.13.0.5924" />
        <PackageReference Include="Emgu.CV.runtime.windows" Version="4.13.0.5924" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.3" />
        <PackageReference Include="System.IO.Ports" Version="8.0.0" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Views\MainWindow\Views\WellsView.axaml.cs">
        <DependentUpon>WellsView.axaml</DependentUpon>
      </Compile>
      <Compile Update="Views\PortsWindow\PortsWindow.axaml.cs">
        <DependentUpon>PortsWindow.axaml</DependentUpon>
      </Compile>
    </ItemGroup>
</Project>
