#pragma once

#include <Arduino.h>
#include <string.h>
#include <stdlib.h>

const char MOVE_BACKWARD_CMD[] PROGMEM = "MOVE_BACKWARD";
const char MOVE_FORWARD_CMD[] PROGMEM = "MOVE_FORWARD";
const char MOVE_LEFT_CMD[] PROGMEM = "MOVE_LEFT";
const char MOVE_RIGHT_CMD[] PROGMEM = "MOVE_RIGHT";
const char MOVE_UP_CMD[] PROGMEM = "MOVE_UP";
const char MOVE_DOWN_CMD[] PROGMEM = "MOVE_DOWN";
const char GO_HOME_CMD[] PROGMEM = "GO_HOME";
const char INC_STEP_CMD[] PROGMEM = "INC_STEP";
const char DEC_STEP_CMD[] PROGMEM = "DEC_STEP";
const char ASPIRATE_CMD[] PROGMEM = "ASPIRATE";
const char DISPENSE_CMD[] PROGMEM = "DISPENSE";
const char CALIBRATE_HOME_CMD[] PROGMEM = "CALIBRATE_HOME";
const char MOVE_HARD_WELL_CMD[] PROGMEM = "MOVE_HARD_WELL";
const char MOVE_CALC_WELL_CMD[] PROGMEM = "MOVE_CALC_WELL";
const char RECORD_POINT_CMD[] PROGMEM = "RECORD_POINT";
const char SOLVE_MAP_CMD[] PROGMEM = "SOLVE_MAP";
const char DELETE_POINT_CMD[] PROGMEM = "DELETE_POINT";
const char CLEAR_CALIBRATION_CMD[] PROGMEM = "CLEAR_CALIBRATION";
const char PARK_CMD[] PROGMEM = "PARK";
const char PRINT_WELL_CMD[] PROGMEM = "PRINT_WELL";
const char PRINT_CALIBRATION_CMD[] PROGMEM = "PRINT_CALIBRATION";
const char PRINT_STEPS_CMD[] PROGMEM = "PRINT_STEPS";
const char CREATE_ACTION_CMD[] PROGMEM = "CREATE_ACTION";
const char UPDATE_ACTION_CMD[] PROGMEM = "UPDATE_ACTION";
const char DEL_ACTION_CMD[] PROGMEM = "DEL_ACTION";
const char LINK_ACTION_WELL_CMD[] PROGMEM = "LINK_ACTION_WELL";
const char UNLINK_ACTION_WELL_CMD[] PROGMEM = "UNLINK_ACTION_WELL";
const char CLEAR_ACTIONS_CMD[] PROGMEM = "CLEAR_ACTIONS";
const char PRINT_ACTIONS_CMD[] PROGMEM = "PRINT_ACTIONS";
const char PRINT_WELL_ACTIONS_CMD[] PROGMEM = "PRINT_WELL_ACTIONS";
const char PRINT_TIME[] PROGMEM = "PRINT_TIME";
const char SET_TIME[] PROGMEM = "SET_TIME";

const uint8_t COMMAND_STRING_SZ = 11;

void parseCommands();